// =============================================================================
// mid-qr — Generator
//
// Wraps the Rust/WASM generate + decode functions with:
//   • Lazy, once-only WASM initialisation (safe to call from multiple places)
//   • Still-image decode via rxing WASM (file uploads, canvas, ImageBitmap)
//   • A clean async API with no module-level side-effects
// =============================================================================

import type { GenerateOptions, MidQrStatus } from './types.js';

// ── WASM module types (generated by wasm-bindgen / wasm-pack) ─────────────────
// We import the types only at the TS level; the actual module is loaded
// dynamically at runtime so bundlers can tree-shake it cleanly.

interface WasmModule {
  default(input?: RequestInfo | URL | Response | BufferSource): Promise<void>;
  generate(options: object): string;
  generateSimple(data: string, size: number, dark: string, light: string): string;
  decodeRgba(rgba: Uint8Array | Uint8ClampedArray, width: number, height: number): string;
  decodeLuma(luma: Uint8Array, width: number, height: number): string;
  rgbaToLuma(rgba: Uint8Array | Uint8ClampedArray): Uint8Array;
  getVersion(): string;
  getSupportedErrorLevels(): string;
  getSupportedGradientDirections(): string;
}

// ── Internal state ────────────────────────────────────────────────────────────

let _wasm: WasmModule | null = null;
let _initPromise: Promise<WasmModule> | null = null;

// ── Lazy init ─────────────────────────────────────────────────────────────────

/**
 * Load and initialise the WASM module exactly once.
 * Safe to call concurrently — all callers await the same Promise.
 *
 * @param wasmUrl  Optional explicit URL to the .wasm binary.
 *                 When omitted the JS glue file's default is used
 *                 (works for bundler environments and relative paths).
 */
async function ensureWasm(wasmUrl?: string | URL): Promise<WasmModule> {
  if (_wasm !== null) return _wasm;

  if (_initPromise !== null) return _initPromise;

  _initPromise = (async (): Promise<WasmModule> => {
    // Dynamic import keeps the WASM out of the initial bundle chunk.
    // The path here is relative to the built dist/ output.
    // Consumers using a bundler should alias 'mid-qr/wasm' to their
    // own copy of the wasm directory.
    const mod = await import('../wasm/mid_qr_wasm.js') as WasmModule;

    // Initialise — pass the explicit .wasm URL if provided, otherwise
    // the JS glue will resolve it relative to import.meta.url.
    if (wasmUrl !== undefined) {
      await mod.default(wasmUrl);
    } else {
      await mod.default();
    }

    _wasm = mod;
    return mod;
  })();

  return _initPromise;
}

// ── Generator class ───────────────────────────────────────────────────────────

/**
 * QR code generator and static-image decoder.
 *
 * ```ts
 * const qr = await MidQrGenerator.create();
 *
 * // Generate
 * const svg = qr.generate({ data: 'https://example.com' });
 * document.getElementById('qr')!.innerHTML = svg;
 *
 * // Generate with gradient + logo
 * const svg = qr.generate({
 *   data:       'https://example.com',
 *   size:       400,
 *   errorLevel: 'H',
 *   gradient:   { direction: 'diagonal', color1: '#8B5CF6', color2: '#06B6D4' },
 *   logo:       { url: '/logo.png', sizeRatio: 0.25,
 *                 border: { color: 'white', width: 3, radius: 4 } }
 * });
 *
 * // Decode a still image
 * const text = await qr.decode(fileInputElement.files![0]);
 * ```
 */
export class MidQrGenerator {
  private readonly _wasm: WasmModule;

  private constructor(wasm: WasmModule) {
    this._wasm = wasm;
  }

  // ── Factory ────────────────────────────────────────────────────────────────

  /**
   * Initialise the WASM module and return a ready-to-use generator.
   *
   * @param wasmUrl  Explicit URL to the `.wasm` binary.
   *                 Required in some deployment environments (e.g. GitHub Pages
   *                 where the base path differs from import.meta.url).
   */
  static async create(wasmUrl?: string | URL): Promise<MidQrGenerator> {
    const wasm = await ensureWasm(wasmUrl);
    return new MidQrGenerator(wasm);
  }

  // ── Generation ─────────────────────────────────────────────────────────────

  /**
   * Generate a QR code and return it as an SVG string.
   *
   * The returned SVG is self-contained — no external resources, no scripts.
   * Set it via `element.innerHTML` or use it as an `<img src>` data-URI.
   *
   * @throws {Error} If data is empty, size is out of range, or a color
   *                 value is malformed.
   */
  generate(options: GenerateOptions): string {
    // Map JS camelCase to Rust snake_case (the WASM binding's serde layer
    // accepts camelCase but we send the plain object and let serde handle it).
    return this._wasm.generate({
      data:       options.data,
      size:       options.size        ?? 300,
      darkColor:  options.darkColor   ?? '#000000',
      lightColor: options.lightColor  ?? '#FFFFFF',
      errorLevel: options.errorLevel  ?? 'M',
      margin:     options.margin      ?? true,
      gradient:   options.gradient,
      logo:       options.logo,
    });
  }

  /**
   * Generate a plain QR code with no options object.
   * Convenience wrapper around {@link generate}.
   */
  generateSimple(
    data:       string,
    size        = 300,
    darkColor   = '#000000',
    lightColor  = '#FFFFFF',
  ): string {
    return this._wasm.generateSimple(data, size, darkColor, lightColor);
  }

  // ── Static-image decode ────────────────────────────────────────────────────

  /**
   * Decode a QR code from a still image source.
   *
   * Accepted sources:
   * - `File` / `Blob`         — user file input
   * - `HTMLImageElement`      — `<img>` element (must be fully loaded)
   * - `HTMLCanvasElement`     — any canvas
   * - `OffscreenCanvas`       — worker canvas
   * - `ImageBitmap`           — from `createImageBitmap()`
   * - `URL` / `string`        — image URL (fetched + decoded)
   *
   * This path uses rxing (ZXing-derived Rust decoder) which is tuned for
   * high-resolution still images.  For real-time camera frames use
   * {@link MidQrScanner} instead.
   *
   * @throws {Error} If no QR code could be found in the image.
   */
  async decode(
    source:
      | File
      | Blob
      | HTMLImageElement
      | HTMLCanvasElement
      | OffscreenCanvas
      | ImageBitmap
      | URL
      | string,
  ): Promise<string> {
    const { width, height, data } = await this._extractImageData(source);
    return this._wasm.decodeRgba(data, width, height);
  }

  /**
   * Convert an RGBA buffer to a luma buffer using the same weights as the
   * nimiq scanner worker (R×77 + G×150 + B×29 >> 8).
   *
   * Useful when you want to call {@link decodeLuma} directly, or when you
   * need to process multiple regions of the same frame without repeating the
   * conversion.
   */
  rgbaToLuma(rgba: Uint8Array | Uint8ClampedArray): Uint8Array {
    return this._wasm.rgbaToLuma(rgba);
  }

  /**
   * Decode a QR code from a pre-computed luma (grayscale) buffer.
   * One byte per pixel, `width * height` bytes total.
   */
  decodeLuma(luma: Uint8Array, width: number, height: number): string {
    return this._wasm.decodeLuma(luma, width, height);
  }

  // ── Info ───────────────────────────────────────────────────────────────────

  /** Library version string (matches Cargo.toml / package.json). */
  get version(): string {
    return this._wasm.getVersion();
  }

  /** Comma-separated accepted error-level strings: "L,M,Q,H" */
  get supportedErrorLevels(): string {
    return this._wasm.getSupportedErrorLevels();
  }

  /** Comma-separated accepted gradient direction strings. */
  get supportedGradientDirections(): string {
    return this._wasm.getSupportedGradientDirections();
  }

  // ── Internal helpers ───────────────────────────────────────────────────────

  /**
   * Render any supported image source to an ImageData-like object.
   * We always go through an OffscreenCanvas so this works in both
   * main-thread and worker contexts.
   */
  private async _extractImageData(
    source:
      | File
      | Blob
      | HTMLImageElement
      | HTMLCanvasElement
      | OffscreenCanvas
      | ImageBitmap
      | URL
      | string,
  ): Promise<{ width: number; height: number; data: Uint8ClampedArray }> {
    // ── Resolve to ImageBitmap ─────────────────────────────────────────────
    let bitmap: ImageBitmap;

    if (source instanceof ImageBitmap) {
      bitmap = source;
    } else if (
      source instanceof HTMLCanvasElement ||
      source instanceof OffscreenCanvas
    ) {
      // Canvas — extract directly without createImageBitmap to avoid
      // premultiplied-alpha issues in some browsers.
      const ctx = (source as HTMLCanvasElement).getContext('2d') as
        | CanvasRenderingContext2D
        | null;
      if (!ctx) throw new Error('mid-qr: could not get 2D context from canvas');
      const id = ctx.getImageData(0, 0, source.width, source.height);
      return { width: id.width, height: id.height, data: id.data };
    } else if (source instanceof HTMLImageElement) {
      if (!source.complete) {
        await new Promise<void>((resolve, reject) => {
          source.onload  = () => resolve();
          source.onerror = () => reject(new Error('mid-qr: image failed to load'));
        });
      }
      bitmap = await createImageBitmap(source);
    } else if (source instanceof File || source instanceof Blob) {
      bitmap = await createImageBitmap(source);
    } else {
      // URL or string — fetch, then decode
      const url = source instanceof URL ? source.href : source;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`mid-qr: failed to fetch image: ${res.status}`);
      const blob = await res.blob();
      bitmap = await createImageBitmap(blob);
    }

    // ── Render bitmap to OffscreenCanvas → ImageData ───────────────────────
    const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
    const ctx    = canvas.getContext('2d');
    if (!ctx) throw new Error('mid-qr: could not create OffscreenCanvas context');

    ctx.drawImage(bitmap, 0, 0);
    const id = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
    return { width: id.width, height: id.height, data: id.data };
  }
}
